#!/usr/bin/quickemu --vm
guest_os="reactos"
disk_img="reactos-nightly/disk.qcow2"
iso="reactos-nightly/reactos-bootcd-0.4.16-dev-2307-g0c4091c-x86-gcc-lin-dbg.iso"
boot="legacy"
disk_size="12G"
ram="2048M"
display="spice"
