#!/usr/bin/quickemu --vm
guest_os="reactos"
disk_img="reactos-latest/disk.qcow2"
iso="reactos-latest/ReactOS-0.4.15-release-1-gdbb43bbaeb2-x86.iso"
boot="legacy"
disk_size="12G"
ram="2048M"
display="spice"
